/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rickandbrandongame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author brand
 */
public class TheGayLauncher extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form TheGayLauncher
     */

    public TheGayLauncher() {
        initComponents();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        launcherMenu = new javax.swing.JPanel();
        playTTTButton = new javax.swing.JButton();
        launcherTitle = new java.awt.Label();
        ticTacToeLogo = new javax.swing.JLabel();
        playTetrisButton = new javax.swing.JButton();
        tetrisLogo = new javax.swing.JLabel();
        launcherSettingsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        launcherMenu.setBackground(new java.awt.Color(43, 43, 43));
        launcherMenu.setMaximumSize(new java.awt.Dimension(1100, 600));
        launcherMenu.setMinimumSize(new java.awt.Dimension(1100, 600));
        launcherMenu.setPreferredSize(new java.awt.Dimension(1100, 600));

        playTTTButton.setBackground(new java.awt.Color(63, 63, 63));
        playTTTButton.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        playTTTButton.setForeground(new java.awt.Color(255, 255, 255));
        playTTTButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        playTTTButton.setLabel("Play Tic-Tac-Toe");
        playTTTButton.setMaximumSize(new java.awt.Dimension(300, 100));
        playTTTButton.setMinimumSize(new java.awt.Dimension(300, 100));
        playTTTButton.setPreferredSize(new java.awt.Dimension(300, 100));
        playTTTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playTTTButtonActionPerformed(evt);
            }
        });

        launcherTitle.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        launcherTitle.setForeground(new java.awt.Color(255, 255, 255));
        launcherTitle.setMaximumSize(new java.awt.Dimension(100, 200));
        launcherTitle.setMinimumSize(new java.awt.Dimension(100, 200));
        launcherTitle.setText("Uber Gay Games™");

        ticTacToeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rickandbrandongame/tic-tac-toe.png"))); // NOI18N
        ticTacToeLogo.setAutoscrolls(true);
        ticTacToeLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ticTacToeLogo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rickandbrandongame/TTT.png"))); // NOI18N
        ticTacToeLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ticTacToeLogo.setInheritsPopupMenu(false);
        ticTacToeLogo.setVerifyInputWhenFocusTarget(false);

        playTetrisButton.setBackground(new java.awt.Color(63, 63, 63));
        playTetrisButton.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        playTetrisButton.setForeground(new java.awt.Color(255, 255, 255));
        playTetrisButton.setText("Play Tetris");
        playTetrisButton.setToolTipText("");
        playTetrisButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        playTetrisButton.setMaximumSize(new java.awt.Dimension(300, 100));
        playTetrisButton.setMinimumSize(new java.awt.Dimension(300, 100));
        playTetrisButton.setPreferredSize(new java.awt.Dimension(300, 100));

        tetrisLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rickandbrandongame/Tetris-logo.png"))); // NOI18N

        launcherSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rickandbrandongame/settings.png"))); // NOI18N

        javax.swing.GroupLayout launcherMenuLayout = new javax.swing.GroupLayout(launcherMenu);
        launcherMenu.setLayout(launcherMenuLayout);
        launcherMenuLayout.setHorizontalGroup(
            launcherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(launcherMenuLayout.createSequentialGroup()
                .addComponent(launcherTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(launcherSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launcherMenuLayout.createSequentialGroup()
                .addGap(0, 407, Short.MAX_VALUE)
                .addGroup(launcherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launcherMenuLayout.createSequentialGroup()
                        .addComponent(tetrisLogo)
                        .addGap(162, 162, 162)
                        .addComponent(ticTacToeLogo)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launcherMenuLayout.createSequentialGroup()
                        .addComponent(playTetrisButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(playTTTButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        launcherMenuLayout.setVerticalGroup(
            launcherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(launcherMenuLayout.createSequentialGroup()
                .addGroup(launcherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launcherMenuLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(tetrisLogo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launcherMenuLayout.createSequentialGroup()
                        .addGroup(launcherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(launcherMenuLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(launcherTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, launcherMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(launcherSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(ticTacToeLogo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(launcherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playTTTButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playTetrisButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(launcherMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(launcherMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void playTTTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playTTTButtonActionPerformed
    java.awt.EventQueue.invokeLater(() -> {
            new HomeMenu().setVisible(true);
        });
    }//GEN-LAST:event_playTTTButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheGayLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheGayLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheGayLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheGayLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TheGayLauncher().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel launcherMenu;
    private javax.swing.JButton launcherSettingsButton;
    private java.awt.Label launcherTitle;
    private javax.swing.JButton playTTTButton;
    private javax.swing.JButton playTetrisButton;
    private javax.swing.JLabel tetrisLogo;
    private javax.swing.JLabel ticTacToeLogo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
