/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rickandbrandongame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author brand
 */
public class TheGayLauncher extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form TheGayLauncher
     */

    public TheGayLauncher() {
        initComponents();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        launcherMenu = new javax.swing.JPanel();
        playTTTButton = new javax.swing.JButton();
        launcherTitle = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        launcherMenu.setBackground(new java.awt.Color(43, 43, 43));
        launcherMenu.setMaximumSize(new java.awt.Dimension(1100, 600));
        launcherMenu.setMinimumSize(new java.awt.Dimension(1100, 600));
        launcherMenu.setPreferredSize(new java.awt.Dimension(1100, 600));

        playTTTButton.setBackground(new java.awt.Color(63, 63, 63));
        playTTTButton.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        playTTTButton.setForeground(new java.awt.Color(255, 255, 255));
        playTTTButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        playTTTButton.setLabel("Play Tic-Tac-Toe");
        playTTTButton.setMaximumSize(new java.awt.Dimension(100, 200));
        playTTTButton.setMinimumSize(new java.awt.Dimension(100, 200));
        playTTTButton.setPreferredSize(new java.awt.Dimension(100, 200));
        playTTTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playTTTButtonActionPerformed(evt);
            }
        });

        launcherTitle.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        launcherTitle.setForeground(new java.awt.Color(255, 255, 255));
        launcherTitle.setMaximumSize(new java.awt.Dimension(100, 200));
        launcherTitle.setMinimumSize(new java.awt.Dimension(100, 200));
        launcherTitle.setText("Uber Gay Games™");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rickandbrandongame/tic-tac-toe.png"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rickandbrandongame/TTT.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jLabel1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout launcherMenuLayout = new javax.swing.GroupLayout(launcherMenu);
        launcherMenu.setLayout(launcherMenuLayout);
        launcherMenuLayout.setHorizontalGroup(
            launcherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(launcherMenuLayout.createSequentialGroup()
                .addComponent(launcherTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launcherMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(playTTTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        launcherMenuLayout.setVerticalGroup(
            launcherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(launcherMenuLayout.createSequentialGroup()
                .addGroup(launcherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(launcherMenuLayout.createSequentialGroup()
                        .addComponent(launcherTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launcherMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(playTTTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(launcherMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(launcherMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void playTTTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playTTTButtonActionPerformed
    java.awt.EventQueue.invokeLater(() -> {
            new HomeMenu().setVisible(true);
        });
    }//GEN-LAST:event_playTTTButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheGayLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheGayLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheGayLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheGayLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TheGayLauncher().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel launcherMenu;
    private java.awt.Label launcherTitle;
    private javax.swing.JButton playTTTButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
